### ISSUE TITLE
Quick resize

### ISSUE THREAD

**Issue by TimUntersberger** [tarkah/grout#17]
Is there currently a setting that makes the grid close after a single resize?

My current workflow is always like this:

1. \<C-M-S>
2. Click on the previous window (#16)
3. Resize using the grid
4. \<C-M-S>

It would be nice if it would be possible to change the workflow to this:

1. \<C-M-S>
2. Click on the previous window (#16)
3. Resize using the grid
4. _Grid gets closed automatically_

I feel like this would feel very nice when the click and drag support (#11) lands.

**Comment by tarkah** [comment]
Good suggestion! I actually do this a lot too. The hotkey will need to be different so it knows to autoclose, maybe <control-winkey-s>?

**Comment by tarkah** [comment]
@TimUntersberger this has been implemented along w/ remembering previous window and click & drag support. It is game changing having all 3 working together! You can configure this quick resize hotkey in the config by adding the following

```yml
# Hotkey to activate grid for a quick resize. Grid will automatically
# close after resize operation. Remove comment to activate.
hotkey_quick_resize: CTRL+ALT+Q
```

**Comment by TimUntersberger** [comment]
@tarkah I Just tried it out and it feels really amazing! Thank you a lot!
