### ISSUE TITLE
How to change hotkey

### ISSUE THREAD

**Issue by PatatasDelPapa** [tarkah/grout#18]
I lost my CTRL key and wanted to know how to configure the hotkeys so I could use other keys.

**Comment by tarkah** [comment]
I need to add a setting to configure this still.

**Comment by tarkah** [comment]
@PatatasDelPapa this feature has just been added, and can be set in the config file with the following

```
# Hotkey to activate. Valid modifiers are CTRL, ALT, SHIFT, WIN
hotkey: CTRL+ALT+S
```

I'll publish a new release shortly so you can use this feature

**Comment by PatatasDelPapa** [comment]
Looking foward to it!
