### ISSUE TITLE
Add configurable profiles

### ISSUE THREAD

**Issue by komawoyo** [tarkah/grout#2]
Possibly a way to remember the windows and their layout with the ability to bind it to a hotkey. Say I want to have a "Programmers" layout on F1 and "Debugging" layout on F2 and "Browsing" layout on F3. Flipping back and forth would be convenient. (Alternatively cycling through the custom layouts with alt+tab, for example, would be nice too). 

Not sure if this idea is useful but pretty cool project so far. Thanks for sharing.

**Comment by tarkah** [comment]
Hey, thanks for the first feature request!

Yeah, I think this would be a good addition. Overall I want to keep grout fairly simple... The idea was something pointy clicky to get the occasional new window to behave. But I think grid persistence is important. And having it remember your grid configuration, per monitor, with some programmable layouts would be great!

**Comment by tarkah** [comment]
I've added some basic grid persistence with #15. Once I add multi-monitor support, I'll add some "profiles" that can be specified for each monitor

**Comment by tarkah** [comment]
I've added multi-monitor support, see #23. Each monitor will remember it's layout.

Now I will add "profiles" that can be toggled (most likely via F-keys) and any layout changes will be saved to that monitor / profile combo.

**Comment by tarkah** [comment]
Profiles have been implemented in [v0.6.0](https://github.com/tarkah/grout/releases/tag/v0.6.0)!
