### ISSUE TITLE
Not an issue, just wanted to say thank you!

### ISSUE THREAD

**Issue by frabert** [tarkah/grout#28]
This is a really nice project, I find it really useful and well made. I couldn't find a way to send you an email, so I thought I'd use the issues :)

**Comment by tarkah** [comment]
Thanks! I really appreciate that.

I saw you created a RIFF decoder. That's funny, I made one a couple months ago as well! Awesome to see yours handles writing chunks. I ported the Atrac3+ audio format from FFmpeg to Rust for a friend to use in his FFIV rust project, and those .at3 files use RIFF containers.
