### ISSUE TITLE
Can't resize maximized applications

### ISSUE THREAD

**Issue by DiXN** [tarkah/grout#29]
Some maximized applications can't be resized. 

I could observe this problem mainly with Electron-based applications: VS Code, GitKraken, Postman etc. 
Other notable applications, that exhibit the same problem are Opera and Spotify.
"Native" applications work fine, when maximized. For example Windows Explorer, Task Manager, Photos app.

All of the mentioned applications work as intended, if they are not maximized.

**Comment by tarkah** [comment]
Thanks for the bug report! I just tried this with vscode maximized and faced the same problem.

I'm thinking I need to use this function with `SW_RESTORE` before I resize the window, to get it out of it's maximized state.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow

**Comment by DiXN** [comment]
Good idea!

Using `ShowWindow` with `SW_RESTORE` seems to work great.

**Comment by tarkah** [comment]
Glad to see it was that easy of a fix! I'll test tomorrow morning and merge. Thanks for the PR!
